Handle actual script failures

diff --git a/.github/workflows/scheduled.yml b/.github/workflows/scheduled.yml
--- a/.github/workflows/scheduled.yml
+++ b/.github/workflows/scheduled.yml
@@ -36,31 +36,37 @@ jobs:
         run: |
           pip install vdf
           python check_regeneration_needed.py
-        continue-on-error: true  # Continue the workflow regardless of the exit code
+          echo "exit_code=$LASTEXITCODE" >> $GITHUB_OUTPUT
       - name: Install CS2
-        if: steps.check_time.outcome == 'success'
+        if: steps.check_time.outputs.exit_code == '0'
         run: |
           $csDir = Join-Path (Get-Location) "cs_go"
           steamcmd +force_install_dir $csDir +login anonymous +app_update ${{ env.CS2_APP_ID }} +quit
       - name: Install Source2Viewer-CLI
-        if: steps.check_time.outcome == 'success'
+        if: steps.check_time.outputs.exit_code == '0'
         run: |
           Invoke-WebRequest -Uri ${{ env.SOURCE2_VIEWER_URL }} -OutFile ".\cli-windows-x64.zip"
           Expand-Archive -Path .\cli-windows-x64.zip -DestinationPath . -Force
       - name: Extract vents
-        if: steps.check_time.outcome == 'success'
+        if: steps.check_time.outputs.exit_code == '0'
         run: |
           Get-ChildItem -Force
           ./generate-map-spawns.ps1
-      - name: No update necessary, but code ran fine
-        if: steps.check_time.outcome == 'failure'
-        run: |
-          echo "No action was needed, skipped regeneration."
       - name: Commit regenerated files
-        if: steps.check_time.outcome == 'success'
+        if: steps.check_time.outputs.exit_code == '0'
         run: |
           git config --global user.name 'Jan-Eric Nitschke'
           git config --global user.email 'JanEricNitschke@users.noreply.github.com'
           git add *.json last_run_time.txt
           git commit -am "Automated changes."
           git push
+      - name: No update necessary, but code ran fine
+        if: steps.check_time.outputs.exit_code == '2'
+        run: |
+          echo "No action was needed, skipped regeneration."
+      - name: Script crashed (Exit Code 1)
+        if: steps.check_time.outputs.exit_code == '1'
+        run: |
+          echo "Script encountered an error. Stopping workflow."
+          exit 1
+
